### PR TITLE
OCmod for Sendcloud

### PR DESCRIPTION
**Pull request by nosite**
Based on the VQmod I made a OCMod.

Tested on a clean 2.0.1.2rc

### CODE REVIEW

**Comment by nosite** [comment]
Updated with link to SendCloud panel...

**Comment by Ecno92** [comment]
Thanks for your pull request. We'll take a look at it soon. 
We're currently quite busy with our platform development, so it may take some days.

I already had a look at your changes and I saw you were using https://panel.sendcloud.nl at several places. I'm sure you can keep a single reference to the URL instead of introducing duplication.
Despite this it looks fine as far as I could see. So many thanks for your efforts!

**Comment by NiekvanderLinden** [comment]
I can't get OCMod to work, @nosite how do you install the extension?

**Comment by nosite** [comment]
Upload the folder Admin and Image, install the OCmod via the Extension Installer in the admin.

**Pull request merged**
